import { Inter } from "next/font/google";
import Head from "next/head";
import Link from "next/link";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <Head>
        {/* Add any head elements you need, such as title and metadata */}
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </Head>
      <body className={`${inter.className} relative h-screen bg-black`}>
       
        <img
          src="./assets/images/Logowhite.png"
          alt="Logo"
          className="w-15 h-20 fixed top-0 left-0 m-4"
        />
        <div className="relative z-10 p-8">{children}</div>
      </body>
    </html>
  );
};

export default RootLayout;
